config/routes.rb
WorkoutTracker::Application.routes.draw do
  resources :user_measurements
  resources :articles
  resources :profiles
  resources :measurements
  resources :excercises
  resources :workouts
  resources :users
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages

  root 'home#index'

  get 'welcome' => 'home#index', as: :welcome
  get 'documentation' => 'home#documentation', as: :documentation

  get 'signup' => 'users#new', as: :signup
  get 'signin' => 'sessions#new', as: :signin
  get 'auth/:provider/callback' => 'sessions#create'
  get 'reset-password' => 'sessions#reset_password', as: :reset_password
  post 'reset-password' => 'sessions#process_reset_password'
  get 'reset-password-finish/:token' => 'sessions#reset_password_finish', as: :reset_password_finish
  post 'reset-password-finish/:token' => 'sessions#reset_password_finish_save'

  get 'toggleown' => 'sessions#toggle_own', as: :toggleown
  delete 'signout' => 'sessions#destroy', as: :signout

  get 'user/:id/profile' => 'users#show_profile', as: :view_profile
  post 'user/myself/set-default-group/:group_id' => 'users#set_default_group', as: :set_my_default_group

  get 'befriend/:id' => 'users#befriend', as: :befriend
  get 'rejectfriendship/:from_id/:to_id' => 'friendships#reject', as: :reject_friendship
  get 'acceptfriendship/:from_id/:to_id' => 'friendships#accept', as: :accept_friendship

  get 'user/my-groups' => 'users#mygroups', as: :mygroups
  post 'user/my-groups' => 'users#mygroups_save'
  get 'user/my-group-edit/:id' => 'users#mygroup_edit', as: :mygroup_edit
  get 'user/groups-i-am-in' => 'users#groups_i_am_in', as: :groups_i_am_in
  get 'user/myself/add-to-group/:group_id' => 'users#add_me_to_group', as: :add_me_to_group
  get 'user/:id/remove-from-group/:group_id' => 'users#remove_user_from_group'
  get 'user/:id/add-to-group/:group_id' => 'users#add_user_to_group'
  get 'user/remove-me-from-group/:id' => 'users#remove_me_from_group', as: :remove_me_from_group
  get 'user/hide-group-from-stream/:id' => 'users#hide_group_from_stream', as: :hide_group_from_stream
  get 'user/show-group-in-stream/:id' => 'users#show_group_in_stream', as: :show_group_in_stream

  get 'workout/:id/join' => 'workouts#join', as: :join_workout

  get 'my-measurements' => 'user_measurements#index', as: :my_measurements

  get 'inbox/:part' => 'messages#index', as: :inbox

  get 'workout-details/:id' => 'workouts#show_details', as: :workout_details

  get 'workout_units/summary' => 'workout_units#summary', as: :workout_units_summary
  get 'workout_units/summary/group/:group_id' => 'workout_units#summary', as: :workout_units_summary_for_group
  resources :workout_unit_types
  resources :workout_units

end

app/controllers/workout_unit_types_controller.rb
class WorkoutUnitTypesController < ApplicationController
  before_action :set_workout_unit_type, only: [:show, :edit, :update, :destroy]

  # GET /workout_unit_types
  # GET /workout_unit_types.json
  def index
    @workout_unit_types = WorkoutUnitType.all
  end

  # GET /workout_unit_types/1
  # GET /workout_unit_types/1.json
  def show
  end

  # GET /workout_unit_types/new
  def new
    @workout_unit_type = WorkoutUnitType.new
  end

  # GET /workout_unit_types/1/edit
  def edit
  end

  # POST /workout_unit_types
  # POST /workout_unit_types.json
  def create
    @workout_unit_type = WorkoutUnitType.new(workout_unit_type_params)

    respond_to do |format|
      if @workout_unit_type.save
        format.html { redirect_to @workout_unit_type, notice: 'Workout unit type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @workout_unit_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @workout_unit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_unit_types/1
  # PATCH/PUT /workout_unit_types/1.json
  def update
    respond_to do |format|
      if @workout_unit_type.update(workout_unit_type_params)
        format.html { redirect_to @workout_unit_type, notice: 'Workout unit type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workout_unit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_unit_types/1
  # DELETE /workout_unit_types/1.json
  def destroy
    @workout_unit_type.destroy
    respond_to do |format|
      format.html { redirect_to workout_unit_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout_unit_type
      @workout_unit_type = WorkoutUnitType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_unit_type_params
      params.require(:workout_unit_type).permit(:name, :category, :difficulty, :description, :icon, :color)
    end
end

app/helpers/workout_unit_types_helper.rb
module WorkoutUnitTypesHelper
end

app/views/workout_unit_types/_form.html.erb
<%= form_for(@workout_unit_type) do |f| %>
  <% if @workout_unit_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout_unit_type.errors.count, "error") %> prohibited this workout_unit_type from being saved:</h2>

      <ul>
      <% @workout_unit_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.number_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workout_unit_types/edit.html.erb
<h1>Editing workout_unit_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout_unit_type %> |
<%= link_to 'Back', workout_unit_types_path %>

app/views/workout_unit_types/index.html.erb
<h1>Listing workout_unit_types</h1>

<table  class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Difficulty</th>
      <th>Description</th>
      <th>Icon</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workout_unit_types.each do |workout_unit_type| %>
      <tr>
        <td><%= workout_unit_type.name %></td>
        <td><%= workout_unit_type.category %></td>
        <td><%= workout_unit_type.difficulty %></td>
        <td><%= workout_unit_type.description %></td>
        <td><%= workout_unit_type.icon %></td>
        <td><%= link_to 'Show', workout_unit_type %></td>
        <td><%= link_to 'Edit', edit_workout_unit_type_path(workout_unit_type) %></td>
        <td><%= link_to 'Destroy', workout_unit_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout unit type', new_workout_unit_type_path %>

app/views/workout_unit_types/new.html.erb
<h1>New workout_unit_type</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_unit_types_path %>

app/views/workout_unit_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workout_unit_type.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @workout_unit_type.category %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @workout_unit_type.difficulty %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workout_unit_type.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @workout_unit_type.icon %>
</p>

<%= link_to 'Edit', edit_workout_unit_type_path(@workout_unit_type) %> |
<%= link_to 'Back', workout_unit_types_path %>