config/routes.rb
WorkoutTracker::Application.routes.draw do
  resources :user_measurements
  resources :articles
  resources :profiles
  resources :measurements
  resources :excercises
  resources :workouts
  resources :users
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages

  root 'home#index'

  get 'welcome' => 'home#index', as: :welcome
  get 'documentation' => 'home#documentation', as: :documentation

  get 'signup' => 'users#new', as: :signup
  get 'signin' => 'sessions#new', as: :signin
  get 'auth/:provider/callback' => 'sessions#create'
  get 'reset-password' => 'sessions#reset_password', as: :reset_password
  post 'reset-password' => 'sessions#process_reset_password'
  get 'reset-password-finish/:token' => 'sessions#reset_password_finish', as: :reset_password_finish
  post 'reset-password-finish/:token' => 'sessions#reset_password_finish_save'

  get 'toggleown' => 'sessions#toggle_own', as: :toggleown
  delete 'signout' => 'sessions#destroy', as: :signout

  get 'user/:id/profile' => 'users#show_profile', as: :view_profile
  post 'user/myself/set-default-group/:group_id' => 'users#set_default_group', as: :set_my_default_group

  get 'befriend/:id' => 'users#befriend', as: :befriend
  get 'rejectfriendship/:from_id/:to_id' => 'friendships#reject', as: :reject_friendship
  get 'acceptfriendship/:from_id/:to_id' => 'friendships#accept', as: :accept_friendship

  get 'user/my-groups' => 'users#mygroups', as: :mygroups
  post 'user/my-groups' => 'users#mygroups_save'
  get 'user/my-group-edit/:id' => 'users#mygroup_edit', as: :mygroup_edit
  get 'user/groups-i-am-in' => 'users#groups_i_am_in', as: :groups_i_am_in
  get 'user/myself/add-to-group/:group_id' => 'users#add_me_to_group', as: :add_me_to_group
  get 'user/:id/remove-from-group/:group_id' => 'users#remove_user_from_group'
  get 'user/:id/add-to-group/:group_id' => 'users#add_user_to_group'
  get 'user/remove-me-from-group/:id' => 'users#remove_me_from_group', as: :remove_me_from_group
  get 'user/hide-group-from-stream/:id' => 'users#hide_group_from_stream', as: :hide_group_from_stream
  get 'user/show-group-in-stream/:id' => 'users#show_group_in_stream', as: :show_group_in_stream

  get 'workout/:id/join' => 'workouts#join', as: :join_workout

  get 'my-measurements' => 'user_measurements#index', as: :my_measurements

  get 'inbox/:part' => 'messages#index', as: :inbox

  get 'workout-details/:id' => 'workouts#show_details', as: :workout_details

  get 'workout_units/summary' => 'workout_units#summary', as: :workout_units_summary
  get 'workout_units/summary/group/:group_id' => 'workout_units#summary', as: :workout_units_summary_for_group
  resources :workout_unit_types
  resources :workout_units

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  before_create :init
  validates :first_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    uniqueness: { case_sensitive: false }  
  #,
  #                  format:     { with: VALID_EMAIL_REGEX },
  #                  uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  has_one :profile
  has_many :workouts
  has_many :received_messages, class_name: "Message", foreign_key: "to_user_id"
  has_many :sent_messages, class_name: "Message", foreign_key: "from_user_id"
  has_many :groups, foreign_key: "owner_id"
  has_many :memberships, :dependent => :destroy
  has_many :workout_joins
  has_many :workout_units
  has_many :measurements, class_name: "UserMeasurement"


  VISIBILITY_TYPES = {
    0 => "only me",
    1 => "my groups",
    2 => "everybody"
  }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def isAdmin?
    self.user_class=="admin"
  end


  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def self.from_omniauth(auth)
    where(email: auth.slice(:email)).first_or_initialize.tap do |user|
      user.first_name = auth.extra.raw_info.first_name
      user.last_name = auth.extra.raw_info.last_name
      user.display_name = auth.name
      user.email = auth.info.email if auth.info.respond_to? :email
      # TODO: i would like to bypass has_secure_password validations
      # HACK: for now i just set password_digest to some nonense
      user.password_digest='nooonseeense'
      user.save validate: false
    end
  end

  def get_display_name
    self.display_name || "#{self.first_name} #{self.last_name}"
  end

  private

    def init
      self.user_class ||= 'user'
    end

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :show_profile]
  skip_before_action :require_login, only: [:new, :create]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if @user.profile
      @profile = @user.profile
    else
      @profile = Profile.new(user_id: @user.id)
      @profile.save
   end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        format.html { 
          sign_in @user
          flash[:notice] = "Welcome to the Workout tracker baby!"
          redirect_to welcome_path
          # redirect_to @user, notice: 'User was successfully created.' 
        }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    isUpdate = params[:action_details]=="update"
    if isUpdate
      #out = CGI.escapeHTML(@user.inspect)
      params[:user].each do |key, value|
        @user[key] = value
      end
      #out += CGI.escapeHTML(@user.inspect)
      #render :text  => out
      #return false
      updated = @user.save(:validate => false)
    else
      updated = @user.update(user_params)
    end
    respond_to do |format|
      if updated
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  # Sends a friend request to target user
  def befriend
    # send a friend request only if there is not one already pending
    friendship = Friendship.where(to_user_id: params[:id], from_user_id: current_user.id).first
    if friendship && friendship.type=="both-ways-unconfirmed"
      # do nothing or display warning?
      flash[:error] = 'There is already pending friend request from you to ' + User.find(params[:id]).email
      # over here i would like to redirect to page where we came from
      redirect_to :back
    else
      # first get information about current friendship status
      friendship = Friendship.where(to_user_id: params[:id], from_user_id: current_user.id).first
      if friendship && friendship.type=="both-ways-confirmed"
        # friendship is already established just give user notice about that
        redirect_to :back, warning: "Friendship with #{User.find(params[:id]).email} is already established"
      else
        # create friend request
        friend_request =  Message.new(from_user_id: current_user.id, to_user_id: params[:id], message_type: "friend-request", status: "pending")
        friend_request.save
        if friendship
          friendship.type = "both-ways-unconfirmed"
        else
          friendship = Friendship.new(from_user_id: current_user.id, to_user_id: params[:id], type: "both-ways-unconfirmed")
        end
        friendship.save
      end
      redirect_to :back, notice: "Friend request to #{User.find(params[:id]).email} was sent"
    end
  end

  def show_profile
    render :profile
  end

  def groups_i_am_in
    @groups = Group.joins(memberships: :user).where('memberships.user_id' => current_user.id)
    @memberships_ids = current_user.memberships.where(:show_in_groups_stream => 1).pluck(:group_id)
    @group = Group.new
    @listing_only = true
    render :mygroups
  end

  def remove_me_from_group
    membership = Membership.where(user_id: current_user.id, group_id: params[:id]).first
    membership.destroy if membership
    redirect_back_or ""
  end

  def hide_group_from_stream
    membership = Membership.where(user_id: current_user.id, group_id: params[:id]).first
    membership.show_in_groups_stream = 0
    membership.save
    redirect_back_or ""
  end

  def show_group_in_stream
    membership = Membership.where(user_id: current_user.id, group_id: params[:id]).first
    membership.show_in_groups_stream = 1
    membership.save
    redirect_back_or ""
  end


  def mygroups
    @groups = current_user.groups
    @group = Group.new
    render :mygroups
  end

  def mygroups_save
    is_update = false
    if params[:commit]=="Create group"
      @group = Group.new(name: params[:name], description: params[:description], summary_from: params[:summary_from][0], public: params[:public], owner_id: current_user.id)
    else
      @group = Group.find(params[:id])
      @group[:name]=params[:name]
      @group[:description]=params[:description]
      @group[:summary_from]=params[:summary_from][0]
      @group[:public]=params[:public]
      is_update = true
    end
    saved = @group.save
    @groups = current_user.groups

    #render :text => params.inspect
    #return

    respond_to do |format|
      if saved
        format.html { 
          if is_update 
            flash[:notice] = 'Group was successfully updated.'
          else
            flash[:notice] = 'New Group was successfully created.'
          end if
          redirect_back_or mygroups_path
        }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'mygroups' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def mygroup_edit
    @group = Group.find(params[:id])
    @members = @group.users.all
    @nonmembers = User.all
    #render :text => CGI.escapeHTML(@members.inspect)
    #render :text => params
    render :mygroupdetail
  end

  def remove_user_from_group
    membership = Membership.where(user_id: params[:id], group_id: params[:group_id]).first
    membership.destroy if membership
    #render :text => params
    #redirect_to "/user/my-group-edit/#{params[:group_id]}"
    redirect_back_or "/user/my-group-edit/#{params[:group_id]}"
  end

  def add_me_to_group
    #render :text => "gonna add #{current_user.get_display_name}"
    membership = Membership.new(user_id: current_user.id, group_id: params[:group_id])
    membership.save
    flash[:notice] = "You were added to #{Group.find(membership.group_id).name} group"
    redirect_to root_path
  end


  def add_user_to_group
    membership = Membership.new(user_id: params[:id], group_id: params[:group_id])
    membership.save
    redirect_back_or "/user/my-group-edit/#{params[:group_id]}"
  end

  def set_default_group
    user = User.find(current_user.id)
    user.default_group_id = params[:group_id]
    user.save(:validate => false)
    redirect_back_or groups_i_am_in_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation, :display_name, :alternative_email, :visibility)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def getNameOrEmail(user)
		if user.display_name && user.display_name!=''
			return user.display_name
		else
			return user.email
		end
	end
end

app/views/users/_form.html.erb
<%= form_for(@user, html:{class: "form-horizontal"}) do |f| %>
  <%#= @user.inspect %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, class: 'col-sm-3 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :email, class: 'form-control' %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :first_name, class: 'col-sm-3 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: 'col-sm-3 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :display_name, class: 'col-sm-3 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :display_name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :alternative_email, class: 'col-sm-3 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :alternative_email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :visibility, 'Visibility of my content', class: 'col-sm-3 control-label' %>
    <div class="col-sm-4">
      <%= f.select :visibility, User::VISIBILITY_TYPES.invert, {prompt: 'select visibility of your content'}, {class: 'form-control'} %>
    </div>
  </div>
  <% if @user.new_record? %>
    <div class="form-group">
      <%= f.label :password, class: 'col-sm-3 control-label' %>
      <div class="col-sm-4">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "Confirmation", class: 'col-sm-3 control-label' %>
      <div class="col-sm-4">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
  <% else %>
    <%= hidden_field_tag "action_details", "update" %>
  <% end %>
  <div class="form-group col-sm-6">
    <div class="pull-right">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/users/_profile.html.erb
<%= form_for(@profile, html:{class: "form-horizontal"}) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :birth_date, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :birth_date, :value => @profile.try(:birth_date).try(:strftime,'%Y-%m-%d %H:%M'), class: 'form-control', :placeholder => "YYYY-MM-DD hh:mm" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :country, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :city, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bio, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_area :bio, size: "80x6", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :height, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :height, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :weight, class: 'col-sm-2 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :weight, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group col-sm-10">
    <div class="pull-right">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="col-sm-6">
	<h1>Editing user</h1>
	<%= render 'form' %>
</div>
<div class="col-sm-6">
	<h1>Profile</h1>
	<%= render 'profile' %>
</div>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Action</th>

    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td>
          <% if user.id != current_user.id %>
            <%= link_to 'Friends', befriend_path(user.id) %>
          <% end %>
          <% if is_admin? %>
            <%= link_to 'Show', user %>
            <%= link_to 'Edit', edit_user_path(user) %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if is_admin? %>
  <%= link_to 'New User', new_user_path %>
<% end %>

app/views/users/mygroupdetail.html.erb
<h1>My group details</h1>

<div class="col-sm-4">
  <h2>Edit group</h2>
  <%= form_tag(mygroups_path, class: "form-horizontal") do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
    </div>
    <div class="form-group">
      <%= label_tag "name", nil, class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= text_field_tag "name", @group.name, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "description", nil, class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= text_area_tag "description", @group.description, rows: 5, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "summary from", nil, class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= date_field "summary_from", nil, value: @group.summary_from.try(:strftime, '%Y-%m-%d'), class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "public", nil, class: 'col-sm-3 control-label' %>
      <div class="col-sm-9">
        <%= check_box_tag "public", 1, @group.public, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <div><label class="col-sm-3 control-label">addme link</label></div>
      <div class="col-sm-9">
          <%= add_me_to_group_url(@group) %>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <% if @group.new_record? %>
        <%= submit_tag "Create group", value: "create", class: "btn btn-large btn-primary pull-right" %>
      <% else %>
        <%= submit_tag "Update group", value: "update", class: "btn btn-large btn-primary pull-right" %>
      <% end %>
      <%= hidden_field_tag "id", @group.id%>
    </div>
  <% end %>
</div>
<div class="col-sm-4">
  <h2>Current members</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Display name</th>
        <th>Email</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @members.each do |user| %>
        <tr>
          <td><%= user.display_name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to 'Remove', "/user/#{user.id}/remove-from-group/#{@group.id}" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>
<div class="col-sm-4">
  <h2>Add members</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Display name</th>
        <th>Email</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @nonmembers.each do |user| %>
        <tr>
          <td><%= user.display_name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to 'Add', "/user/#{user.id}/add-to-group/#{@group.id}" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/mygroups.html.erb
<% if @listing_only %>
  <h1>Groups i'm member of</h1>
<% else %>
  <h1>My groups</h1>
<% end %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Members</th>
      <th>Action</th>

    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td class="col-sm-1"><%= group.name %></td>
        <td class="col-sm-1"><%= group.description %></td>
        <td class="col-sm-8">
          <% group.users.each do |user| %>
            <%= link_to user.email, view_profile_path(user.id) %>,
          <% end %>
        </td>

        <td>
          <% if @listing_only %>
            <% if group.id != current_user.default_group_id %>
              <%= link_to 'Set default', set_my_default_group_path(group),  method: :post %>
            <% end %>
            <%= link_to 'Remove me', remove_me_from_group_path(id: group.id) %>
            <% if @memberships_ids.include? group.id %>
              <%= link_to 'Hide from stream', hide_group_from_stream_path(id: group.id) %>
            <% else %>
              <%= link_to 'Show in stream', show_group_in_stream_path(id: group.id) %>
            <% end %>
          <% else %>
            <%= link_to 'Edit & members', mygroup_edit_path(id: group.id) %>
            <%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if !@listing_only %>
  <br><br>
  <hr style="border-top: 1px solid lightgrey">
  <h2>Add new group</h2>
  <%= form_tag(mygroups_path, class: "form-horizontal") do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
    </div>
    <div class="form-group">
      <%= label_tag "name", nil, class: 'col-sm-1 control-label' %>
      <div class="col-sm-4">
        <%= text_field_tag "name", @group.name, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "description", nil, class: 'col-sm-1 control-label' %>
      <div class="col-sm-4">
        <%= text_area_tag "description", @group.description, rows: 5, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "public", nil, class: 'col-sm-1 control-label' %>
      <div class="col-sm-4">
        <%= check_box_tag "public", 1, @group.public, class: 'form-control'%>
      </div>
    </div>
    <div class="form-group col-sm-5">
      <%= submit_tag "Create group", class: "btn btn-large btn-primary pull-right" %>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-offset-1">
		<h1>New user</h1>
		<%= render 'form' %>
		<%#= link_to 'Back', users_path %>
 </div>
</div>

app/views/users/profile.html.erb
<div class="col-sm-6">
	<h1>User: <%= @user.email %></h1>
	<div class="row">
		<div class="col-sm-3 text-right"><strong>first name:</strong></div>
		<div class="col-sm-6"><%= @user.first_name %></div>
	</div>
	<div class="row">
		<div class="col-sm-3 text-right"><strong>last name:</strong></div>
		<div class="col-sm-6"><%= @user.last_name %></div>
	</div>
	<div class="row">
		<div class="col-sm-3 text-right"><strong>display_name:</strong></div>
		<div class="col-sm-6"><%= @user.display_name %></div>
	</div>
</div>
<div class="col-sm-6">
	<% if @user.profile %>
	<h1>Profile</h1>
		<div class="row">
			<div class="col-sm-3 text-right"><strong>birth_date:</strong></div>
			<div class="col-sm-6"><%= @user.profile.birth_date %></div>
		</div>
		<div class="row">
			<div class="col-sm-3 text-right"><strong>country:</strong></div>
			<div class="col-sm-6"><%= @user.profile.country %></div>
		</div>
		<div class="row">
			<div class="col-sm-3 text-right"><strong>city:</strong></div>
			<div class="col-sm-6"><%= @user.profile.city %></div>
		</div>
		<div class="row">
			<div class="col-sm-3 text-right"><strong>bio:</strong></div>
			<div class="col-sm-6"><%= raw @user.profile.bio.try(:gsub, /\n/, '<br>') %></div>
		</div>
		<div class="row">
			<div class="col-sm-3 text-right"><strong>weight:</strong></div>
			<div class="col-sm-6"><%= @user.profile.weight %></div>
		</div>
		<div class="row">
			<div class="col-sm-3 text-right"><strong>height:</strong></div>
			<div class="col-sm-6"><%= @user.profile.height %></div>
		</div>
	<% end %>
</div>

<div class="clearfix">
</div>

<br><br>
<p>
	<%= link_to 'Back', :back %>
</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Display name:</strong>
  <%= @user.display_name %>
</p>

<p>
  <strong>Alternative email:</strong>
  <%= @user.alternative_email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>