config/routes.rb
WorkoutTracker::Application.routes.draw do
  resources :user_measurements
  resources :articles
  resources :profiles
  resources :measurements
  resources :excercises
  resources :workouts
  resources :users
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages

  root 'home#index'

  get 'welcome' => 'home#index', as: :welcome
  get 'documentation' => 'home#documentation', as: :documentation

  get 'signup' => 'users#new', as: :signup
  get 'signin' => 'sessions#new', as: :signin
  get 'auth/:provider/callback' => 'sessions#create'
  get 'reset-password' => 'sessions#reset_password', as: :reset_password
  post 'reset-password' => 'sessions#process_reset_password'
  get 'reset-password-finish/:token' => 'sessions#reset_password_finish', as: :reset_password_finish
  post 'reset-password-finish/:token' => 'sessions#reset_password_finish_save'

  get 'toggleown' => 'sessions#toggle_own', as: :toggleown
  delete 'signout' => 'sessions#destroy', as: :signout

  get 'user/:id/profile' => 'users#show_profile', as: :view_profile
  post 'user/myself/set-default-group/:group_id' => 'users#set_default_group', as: :set_my_default_group

  get 'befriend/:id' => 'users#befriend', as: :befriend
  get 'rejectfriendship/:from_id/:to_id' => 'friendships#reject', as: :reject_friendship
  get 'acceptfriendship/:from_id/:to_id' => 'friendships#accept', as: :accept_friendship

  get 'user/my-groups' => 'users#mygroups', as: :mygroups
  post 'user/my-groups' => 'users#mygroups_save'
  get 'user/my-group-edit/:id' => 'users#mygroup_edit', as: :mygroup_edit
  get 'user/groups-i-am-in' => 'users#groups_i_am_in', as: :groups_i_am_in
  get 'user/myself/add-to-group/:group_id' => 'users#add_me_to_group', as: :add_me_to_group
  get 'user/:id/remove-from-group/:group_id' => 'users#remove_user_from_group'
  get 'user/:id/add-to-group/:group_id' => 'users#add_user_to_group'
  get 'user/remove-me-from-group/:id' => 'users#remove_me_from_group', as: :remove_me_from_group
  get 'user/hide-group-from-stream/:id' => 'users#hide_group_from_stream', as: :hide_group_from_stream
  get 'user/show-group-in-stream/:id' => 'users#show_group_in_stream', as: :show_group_in_stream

  get 'workout/:id/join' => 'workouts#join', as: :join_workout

  get 'my-measurements' => 'user_measurements#index', as: :my_measurements

  get 'inbox/:part' => 'messages#index', as: :inbox

  get 'workout-details/:id' => 'workouts#show_details', as: :workout_details

  get 'workout_units/summary' => 'workout_units#summary', as: :workout_units_summary
  get 'workout_units/summary/group/:group_id' => 'workout_units#summary', as: :workout_units_summary_for_group
  resources :workout_unit_types
  resources :workout_units

end

app/models/workout_unit.rb
class WorkoutUnit < ActiveRecord::Base
	belongs_to :workout_unit_type
end

app/models/workout_unit_type.rb
class WorkoutUnitType < ActiveRecord::Base
end

app/controllers/workout_units_controller.rb
class WorkoutUnitsController < ApplicationController
  before_action :set_workout_unit, only: [:show, :edit, :update, :destroy]

  # GET /workout_units
  # GET /workout_units.json
  def index
    @workout_units = WorkoutUnit.all
  end

  # GET /workout_units/1
  # GET /workout_units/1.json
  def show
  end

  # GET /workout_units/new
  def new
    @workout_unit = WorkoutUnit.new
  end

  # GET /workout_units/1/edit
  def edit
  end

  # POST /workout_units
  # POST /workout_units.json
  def create
    @workout_unit = WorkoutUnit.new(workout_unit_params)
    @workout_unit.user_id = current_user.id
    respond_to do |format|
      if @workout_unit.save
        format.html { redirect_to @workout_unit, notice: 'Workout unit was successfully created.' }
        format.json { 
          render :json => @workout_unit.as_json(:include => :workout_unit_type), action: 'show', status: :created, location: @workout_unit 
        }
      else
        format.html { render action: 'new' }
        format.json { render json: @workout_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_units/1
  # PATCH/PUT /workout_units/1.json
  def update
    respond_to do |format|
      if @workout_unit.update(workout_unit_params)
        format.html { redirect_to @workout_unit, notice: 'Workout unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workout_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_units/1
  # DELETE /workout_units/1.json
  def destroy
    if @workout_unit.user_id == current_user.id
      @workout_unit.destroy
      respond_to do |format|
        format.html { redirect_to workout_units_url }
        format.json { head :no_content }
      end
    end
  end

  def summary
    # we need list of users that are going to be displayed (=they have something logged in)
    group = nil
    if (params[:group_id])
      group = Group.find(params[:group_id])
      users = User
        .where(id: WorkoutUnit.uniq.pluck(:user_id))
        .where("id in (select distinct user_id from memberships where group_id=#{params[:group_id]})")
    else
      if current_user.default_group_id.blank?
        users = [current_user]
      else
        group = current_user.default_group_id
        users = User
          .where(id: WorkoutUnit.uniq.pluck(:user_id))
          .where("id in (select distinct user_id from memberships where group_id=#{current_user.default_group_id})")
#          .where("id in (
#              select distinct user_id from memberships where group_id in (
#                select distinct group_id from memberships where user_id=#{current_user.id}
#              )
#            )")
      end
    end

    @users_hash = {}
    user_ids = []
    users.each do |u|
      @users_hash[u.id] = u.attributes
      @users_hash[u.id]["display_name"]=u.get_display_name
      user_ids << u.id
    end

    # we also need sum of point they get
    if group
      date_from = group.summary_from.try(:strftime, '%Y.%m.%d') || '1900.1.1'  
    else
      date_from = '1900.1.1'
    end
    query = "select user_id, sum(difficulty) from workout_units wu
      left join workout_unit_types wut on wut.id = wu.workout_unit_type_id
      where wu.date > '#{date_from}'
      group by user_id"
    
    results = ActiveRecord::Base.connection.execute(query)
    results.each do |r|
      #HACK: this is brutal, we are processing unnecessary records, fix soon
      @users_hash[r[0]]["total"]=r[1] if user_ids.include? r[0]
    end

    # and we need to have all recorder workout units stored in the hash[:user_id][:date][]
    wus = WorkoutUnit.joins(:workout_unit_type).load
    @wus_hash = {}
    wus.each do |wu|
      @wus_hash[wu.user_id] ||= {}
      @wus_hash[wu.user_id][wu.date.strftime('%Y-%m-%d')] ||= []
      @wus_hash[wu.user_id][wu.date.strftime('%Y-%m-%d')] << wu
    end

    # we also want to have list of groups user is a member to draw links for "different" summaries
    @groups = Group.where(id: current_user.memberships.pluck(:group_id))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout_unit
      @workout_unit = WorkoutUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_unit_params
      params.require(:workout_unit).permit(:date, :workout_unit_type_id)
    end
end

app/helpers/workout_units_helper.rb
module WorkoutUnitsHelper
	def draw_summary_calendar
		total_score = 0
		out = "<span style='display:none' id='selectedDate' data-date_long='' data-linked_cell=''></span>"
		out += "<table class=\"calendar pull-left\" style=\"margin-bottom: 0px;\"><tr>"
		now = DateTime.now
		out += "<td style='width: 250px;'></td>"
		(-20..0).each do |i|
			current_day = now + i.days
			out+="<td style=\"width: 40px; padding: 8px 3px 8px 3px;\" >#{current_day.strftime("%d/%m")}</td>"
		end
		out+="<td>total</td>"

		@users_hash.keys.each do |user_id|
			out+="<tr>"
			out += "<td style='width: 150px;'>#{@users_hash[user_id]["display_name"]}</td>"
			(-20..0).each do |i|
				current_day = now + i.days
				wus = @wus_hash[user_id][current_day.strftime('%Y-%m-%d')]
				out+="<td id='day-score-#{current_day.strftime("%d-%m")}' style=\"width: 40px; padding: 8px 3px 8px 3px;\">"
				#out+=wus.inspect
				#out+="<div><a class='testElement'>test</a></div>"
				if wus
					wus.each do |wu|
						#out+=wu.workout_unit_type.inspect
						total_score += wu.workout_unit_type.difficulty
						out+="<div data-id='#{wu.id}' data-toggle='tooltip' title='+#{wu.workout_unit_type.difficulty} - #{wu.workout_unit_type.category}/#{wu.workout_unit_type.name}' class='workout-unit-item' style='width: 40px; background-color: #{wu.workout_unit_type.color}'>+#{wu.workout_unit_type.difficulty}</div>"
					end
				end
				out+="</td>"
			end
			out+="<td style='align:center;'>"
			out+="<span style='background-color:orange; font-size: 30px;'> #{@users_hash[user_id]["total"]} </span>"
			out+="</td>"
			out+="</tr>"
		end
		out+="</table>"
		out
	end
end

app/views/workout_units/_form.html.erb
<%= form_for(@workout_unit) do |f| %>
  <% if @workout_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout_unit.errors.count, "error") %> prohibited this workout_unit from being saved:</h2>

      <ul>
      <% @workout_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :workout_unit_type_id %><br>
    <%= f.number_field :workout_unit_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workout_units/edit.html.erb
<h1>Editing workout_unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout_unit %> |
<%= link_to 'Back', workout_units_path %>

app/views/workout_units/index.html.erb
<h1>Listing workout_units</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Workout unit type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @workout_units.each do |workout_unit| %>
      <tr>
        <td><%= workout_unit.date %></td>
        <td><%= workout_unit.workout_unit_type_id %></td>
        <td><%= link_to 'Show', workout_unit %></td>
        <td><%= link_to 'Edit', edit_workout_unit_path(workout_unit) %></td>
        <td><%= link_to 'Destroy', workout_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout unit', new_workout_unit_path %>

app/views/workout_units/new.html.erb
<h1>New workout_unit</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_units_path %>

app/views/workout_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @workout_unit.date %>
</p>

<p>
  <strong>Workout unit type:</strong>
  <%= @workout_unit.workout_unit_type_id %>
</p>

<%= link_to 'Edit', edit_workout_unit_path(@workout_unit) %> |
<%= link_to 'Back', workout_units_path %>

app/views/workout_units/summary.html.erb
<h1>YB tracker summary </h1>
<div>
	<%= raw draw_summary_calendar %>
	<div class="clearfix">&nbsp;</div>
	<br>
	Show summary for group: 
	<% @groups.each do |group| %>
	  <%= link_to group.name, workout_units_summary_for_group_path(group)%>
	<% end %>
</div>