config/routes.rb
WorkoutTracker::Application.routes.draw do
  resources :user_measurements
  resources :articles
  resources :profiles
  resources :measurements
  resources :excercises
  resources :workouts
  resources :users
  resources :groups
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages

  root 'home#index'

  get 'welcome' => 'home#index', as: :welcome
  get 'documentation' => 'home#documentation', as: :documentation

  get 'signup' => 'users#new', as: :signup
  get 'signin' => 'sessions#new', as: :signin
  get 'auth/:provider/callback' => 'sessions#create'
  get 'reset-password' => 'sessions#reset_password', as: :reset_password
  post 'reset-password' => 'sessions#process_reset_password'
  get 'reset-password-finish/:token' => 'sessions#reset_password_finish', as: :reset_password_finish
  post 'reset-password-finish/:token' => 'sessions#reset_password_finish_save'

  get 'toggleown' => 'sessions#toggle_own', as: :toggleown
  delete 'signout' => 'sessions#destroy', as: :signout

  get 'user/:id/profile' => 'users#show_profile', as: :view_profile
  post 'user/myself/set-default-group/:group_id' => 'users#set_default_group', as: :set_my_default_group

  get 'befriend/:id' => 'users#befriend', as: :befriend
  get 'rejectfriendship/:from_id/:to_id' => 'friendships#reject', as: :reject_friendship
  get 'acceptfriendship/:from_id/:to_id' => 'friendships#accept', as: :accept_friendship

  get 'user/my-groups' => 'users#mygroups', as: :mygroups
  post 'user/my-groups' => 'users#mygroups_save'
  get 'user/my-group-edit/:id' => 'users#mygroup_edit', as: :mygroup_edit
  get 'user/groups-i-am-in' => 'users#groups_i_am_in', as: :groups_i_am_in
  get 'user/myself/add-to-group/:group_id' => 'users#add_me_to_group', as: :add_me_to_group
  get 'user/:id/remove-from-group/:group_id' => 'users#remove_user_from_group'
  get 'user/:id/add-to-group/:group_id' => 'users#add_user_to_group'
  get 'user/remove-me-from-group/:id' => 'users#remove_me_from_group', as: :remove_me_from_group
  get 'user/hide-group-from-stream/:id' => 'users#hide_group_from_stream', as: :hide_group_from_stream
  get 'user/show-group-in-stream/:id' => 'users#show_group_in_stream', as: :show_group_in_stream

  get 'workout/:id/join' => 'workouts#join', as: :join_workout

  get 'my-measurements' => 'user_measurements#index', as: :my_measurements

  get 'inbox/:part' => 'messages#index', as: :inbox

  get 'workout-details/:id' => 'workouts#show_details', as: :workout_details

  get 'workout_units/summary' => 'workout_units#summary', as: :workout_units_summary
  get 'workout_units/summary/group/:group_id' => 'workout_units#summary', as: :workout_units_summary_for_group
  resources :workout_unit_types
  resources :workout_units

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :require_login

	def index
		# we are going to list workouts stream
		# for start we just display all workouts, newest first
    @workouts = Workout.public_scope.order('date DESC')
		@groupworkouts = Workout
      .unscoped
      .includes(:user)
      .where(
  			"user_id in 
  				(select user_id from memberships where group_id in 
  						(select group_id from memberships where user_id=#{current_user.id} and show_in_groups_stream = 1)
  				)")
      .where("users.visibility>0")
      .order('date DESC') if (current_user) 
		@news = Article.all.order('updated_at DESC').limit(5)
    @excercises = Excercise.all
	end

  def documentation
  end
end

app/helpers/home_helper.rb
module HomeHelper
	def draw_calendar
		total_score = 0
		out = "<span style='display:none' id='selectedDate' data-date_long='' data-linked_cell=''></span>"
		out += "<table class=\"calendar homepage pull-left\" style=\"margin-bottom: 0px;\"><tr>"
		now = DateTime.now
		(-12..0).each do |i|
			current_day = now + i.days
			out+="<td style=\"width: 40px; padding: 8px 3px 8px 3px;\" data-date_short='#{current_day.strftime("%d/%m")}' data-linked_cell='#{current_day.strftime("%d-%m")}' data-date_long='#{current_day.strftime("%Y/%m/%d")}'>#{current_day.strftime("%d/%m")}</td>"
		end
		out+="<tr>"
		(-12..0).each do |i|
			current_day = now + i.days
			wus = current_user.workout_units.joins(:workout_unit_type).where("DATE_FORMAT(date,'%Y-%m-%d')='#{current_day.strftime('%Y-%m-%d')}'")
			out+="<td id='day-score-#{current_day.strftime("%d-%m")}' style=\"width: 40px; padding: 8px 3px 8px 3px;\">"
			#out+="<div><a class='testElement'>test</a></div>"
			wus.each do |wu|
				#out+=wu.workout_unit_type.inspect
				total_score += wu.workout_unit_type.difficulty
				out+="<div data-id='#{wu.id}' data-toggle='tooltip' title='+#{wu.workout_unit_type.difficulty} - #{wu.workout_unit_type.category}/#{wu.workout_unit_type.name}' class='workout-unit-item' style='width: 40px; background-color: #{wu.workout_unit_type.color}'>+#{wu.workout_unit_type.difficulty}</div>"
			end
			out+="</td>"
		end
		out+="</tr>"
		out+="</table>"
		out+="<div style='float:left'>Your total <br> score is: <br><br><span style='background-color:orange; font-size: 40px;'> #{total_score} </span></div>"
	end

	def workout_unit_selector(js_callback_function_name)
		out="<div class='modal' id='selectWorkoutUnit'>"
		out+="<div class='modal-dialog'>"
		WorkoutUnitType.all.each do |wut|
			out += "<button onclick='#{js_callback_function_name}(#{wut.id})' style='width: 200px; border: 0px; margin: 1px; background-color: #{wut.color}'>#{wut.name}</button><br>"
		end
		out +="</div>"
		out +="</div>"
	end
end

app/views/home/documentation.html.erb
<h1>Documentation</h1>

<h3>Workout unit tracker (YB Tracker)</p>
<p>
	<strong>Add workout unit:</strong> Click on '+' sign in the 'calendar' and then choose workout unit type<br>
	<strong>Remove workout unit:</strong> Shift + click on the workout to be removed, either in small 'calendar' or in group summary 
	<br><br>
	<strong>On the summary page</strong>
	<br>
	you can see workouts of all people in your default group ot you can select summary for any of groups you are member of
</p>

<p>
	<strong>Setting default group</strong> can be done in account -> groups i'm in by clicking on set default action of the chosen group
</p>

app/views/home/index.html.erb
<div class="center hero-unit">
  <!--
  <h1>Welcome to the Workout tracker</h1>
  -->
  <% if signed_in? %>
    <!--
  	<p>You are signed in as: <%= current_user.email %>, class: <%= current_user.user_class%></p>
  	<p>
  		<%= link_to "Log out!", signout_path, method: "delete", class: "btn btn-large btn-success" %>
  	</p>
    -->
  <% else %>
    <h1>Welcome to the Workout tracker</h1>
  
  	<p>
      <%= link_to "Login with facebook!", "/auth/facebook", class: "btn btn-large btn-info" %>
      <%= link_to "Sign in!", signin_path, class: "btn btn-large btn-success" %>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
		</p>
  <% end %>

  <% if signed_in? %>
    <div class="col-sm-6">
      <h1>YB Tracker</h1>
			<!-- YB practice units tracker -->
			<div>
				<%= raw workout_unit_selector "window.wt.selectWorkoutUnit" %>
				<%= raw draw_calendar %>
			</div>
			<!-- end of YB practice units tracker -->
	    <div class="clearfix"></div>
      Click on the day (that changes to + sign) to add workout unit. To remove workout unit hold shift and click on it.
      <br>
      <%= link_to "YB Tracker details", workout_units_summary_path %>
	    <div style="height:20px;"></div>

      <h1>NEWS !!!</h1>
      <hr style="border-top: 1px solid black; margin:0px 0 10px 0">
      <div style="border: 1px dotted; max-height: 300px; overflow-y: scroll;">
	      <% @news.each do |news| %>
	        <div>
	          <div class="news-title">
	            <h3 style="display: inline"><%= news.title %></h3>
	            written by: 
	              <%= link_to getNameOrEmail(news.user), view_profile_path(news.user.id), :style => 'color: #AA55CC' %>
	            </div>
	          <div class="news-content" style="margin-top: 10px"><%= raw news.content.gsub(/\n/, '<br>') %></div>
	        </div>
	      <% end %>
	    </div>
    </div>


    <div class="col-sm-3">
      <h2>Excercises</h2>
      <div style="height: 200px; overflow-y: scroll; border: 1px dotted">
        <table class="table table-striped">
          <tbody>
            <% if @excercises %>
              <% @excercises.each do |excercise| %>
                <tr>
                  <td>
                    <%= link_to excercise.name, excercise_path(excercise.id), :style =>'border-bottom:1px dotted;' %>
                    by:
                    <span style="color: #AA55CC">
                      <%= link_to getNameOrEmail(excercise.user), view_profile_path(excercise.user.id), :style => 'color: #AA55CC' %>
                    </span>
                    <%= time_ago_in_words(excercise.updated_at) %> ago
                  </td>
                  <td class="text-left">
                    
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


    <div class="col-sm-3">
      <h2>My Groups Wrkts</h2>

      <div style="height: 200px; overflow-y: scroll; border: 1px dotted">
        <table class="table table-striped">
          <tbody>
            <% if @groupworkouts %>
              <% @groupworkouts.each do |workout| %>
                <tr>
                  <td>
                    <span style="color: #AA55CC">
                      <%= link_to getNameOrEmail(workout.user), view_profile_path(workout.user.id), :style => 'color: #AA55CC' %>:
                    </span>
                    <%= link_to workout.title, workout_details_path(workout.id), :style =>'border-bottom:1px dotted;' %>
                    <% if workout.workout_joins.count > 0 %>
                      with:
                      <% workout.workout_joins.each do |wj| %>
                        <%= link_to getNameOrEmail(User.find(wj.user_id)), view_profile_path(User.find(wj.user_id).id), :style => 'color: #8888EE' %>,
                      <% end %>
                    <% end %>
                    <%= time_ago_in_words(workout.date) %> ago
                    <%= link_to "[join]", join_workout_path(workout.id) %>
                  </td>
                  <td class="text-left">
                    
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>

      <div>&nbsp;</div>
      
      <h2>All Workouts</h2>
      <div style="height: 200px; overflow-y: scroll; border: 1px dotted">
        <table class="table table-striped">
          <tbody>
            <% @workouts.each do |workout| %>
              <tr>
                <td>
                  <span style="color: #AA55CC">
                    <% if workout.user.display_name && workout.user.display_name!='' %>
                      <%= workout.user.display_name %>
                    <% else %> 
                      <%= workout.user.email %>
                    <% end %>
                  </span>
                  logged: 
                  <%= link_to workout.title, workout_details_path(workout.id) %>
                  at: 
                  <%= workout.date %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>


    </div>
  <% end %>
</div>